title: Hello Deploy Now built with Beautiful Jekyll
author: pepperinsalt
navbar-links:
  About Me: "about"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn Markdown: "https://www.markdownguide.org"

theme: beautiful-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-paginate

# Beautiful Jekyll settings
footer-links-list:
  rss: ""
  email: "your-email@example.com"
  twitter: "jekyllrb"
  github: "pepperinsalt"

# Build settings
paginate: 5
paginate_path: "/page:num/"
